version: '3'

services:
  # Game server
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_gs:v0.3
    volumes:
      - "${SHARED_DIR}/:/home"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${BILLING_PORT}:${BILLING_PORT}"
    restart: ${RESTART}
    links:
      - tlmysql
      - nginx
  # Game database
  tlmysql:
    build:
      context: ./services/tlmysql
    image: registry.cn-hangzhou.aliyuncs.com/yulinzhihou/tlsf_tlbbdbserver:v0.1
    volumes:
      - "${SHARED_DIR}/tlbbdb/mysql:/var/lib/mysql"
      - "${SHARED_DIR}/webdb/mysql:/var/lib/mysql"
    ports:
      - "${TLBB_MYSQL_PORT}:${HOST_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${TLBBDB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE_TLBB: "tlbbdb"
      MYSQL_DATABASE_WEB: "webdb"
    restart: ${RESTART}
  # Web database
  nginx:
    build:
      context: ./services/nginx
    volumes:
    - "${SHARED_DIR}/www/:/home/www"
    ports:
    - "${WEB_MYSQL_PORT}:${HOST_MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${WEBDB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "web"
    restart: ${RESTART}